log_moves = true
confirm_moves = true

[[sources]]
dir_pattern = "/Volumes/*/DCIM/*/"
file_regex = "^\\w+([.]\\w+)+$"

[[destinations]]
dir_pattern = "~/Pictures/library/%Y/%b/"
file_pattern = "{parent}_{name}{suffix}.{extensions}"

[[destinations.ignore]]
dir_pattern = "~/Pictures/rejects/"
file_regex = "^\\w+([.]\\w+)+$"
